:construction: Se agrega post de pycon 2024 close #108
python-chile/pythonchile.cl pull request #109
Opened 2024-12-22 02:52 UTC by KrlitosForever

Se agrega post pycon 2024 para su revisión.

2024-12-22 04:04 UTC, pablolirag commented
- Logotipo de pycon  menor tamaño y centrado.
- Seleccionar mejores fotografias y menor tamaño  y poner un titulo descriptivos.
- Usar palabra pyconchile por temas de SEO  y no solo pycon.
- Link del sitio pycon.cl 
- Link de youtube para buscar la grabación de la conferencia.
- Los parrafos  con mas contenido.
- Parrafo con auspiciadores.
- Fotos de menor resolucion y en webp.

2024-12-22 22:35 UTC, ancaneo requested changes

2024-12-22 22:35 UTC, ancaneo commented on content/2024-12-21-Pycon2024.md
> +El pasado **30 de noviembre**, se celebró la tan esperada **PYCON**, un evento organizado por la **Comunidad Python Chile** en la sede **DuocUC San Joaquín**. Fue un día repleto de inspiración, apren
En oración 1, aludir al evento como "PyCon Chile 2024"  en vez de PYCON que es un término que no refiere a un único evento.
En oración 2 donde dice "la sede DuocUC San Joaquín", considero mejor "la institución DUOC UC sede San Joaquín".

2024-12-22 22:35 UTC, ancaneo commented on content/2024-12-21-Pycon2024.md
> +Tuvimos el privilegio de contar con **Denny Pérez**, quien abrió el evento con una **keynote** de primer nivel sobre **Python y Comunidad**, destacando el impacto global de este lenguaje y su increíb
En inicio de sugunda oración "Luego" en vez de "Además" da más sentido de continuidad temporal. "Además" tiene más sentido usarlo en un proceso simultáneo. 
Me parece más justo agregar palabras para cada charla así como se hizo con la de Andrés y Denny.

2025-01-17 01:25 UTC, KrlitosForever commented on content/2024-12-21-Pycon2024.md
> +El pasado **30 de noviembre**, se celebró la tan esperada **PYCON**, un evento organizado por la **Comunidad Python Chile** en la sede **DuocUC San Joaquín**. Fue un día repleto de inspiración, apren
Pablo aplica cambios

2025-01-17 13:31 UTC, KrlitosForever commented on content/2024-12-21-Pycon2024.md
> +<center><img src="images/pycon2024/pycon2024.webp" width="100%" height="100%"/></center>
```suggestion
<center><img src="images/pycon2024/pycon2024.webp" width="100%" height="100%"/></center>
```

2025-01-17 14:54 UTC, KrlitosForever reviewed
Excelente!

2025-01-17 14:54 UTC, KrlitosForever commented on content/2024-12-21-Pycon2024.md
> +<center><img src="images/pycon2024/pycon2024.webp" width="100%" height="100%"/></center>
@pablolirag parece que esa foto no la cargaste "pycon2024.webp"

2025-01-17 16:35 UTC, ancaneo approved these changes

2025-01-18 21:04 UTC, merged