Fix apariencia movil
python-chile/pythonchile.cl pull request #41
Opened 2021-04-23 20:10 UTC by elkabuitrago

Ajustes de apariencia en móvil en el index
base-index.html
cl.css

2021-04-23 21:09 UTC, cmaureir reviewed
![Screen Shot 2021-04-24 at 23 07 12](https://user-images.githubusercontent.com/177982/115929984-fce05580-a488-11eb-9ab3-58c46aecc45a.png)

Sabes si se puede hacer algo para quitar el texto que acompaña al logo o disminuir su trabajo?
Sigo viendo el index mal en móvil.

Lo otro, es que veo que este PR tiene conflictos, porque quizás no actualizaste el repo antes de hacer los cambios, tendrías que resolverlos y luego hacer un merge.

2021-05-02 22:06 UTC, elkabuitrago commented
Ya hice resolví los conflictos. Cuando hice el pull en local me dió conflicto, pero yo misma había hecho el merge del pull request, no entendí (?)
voy a trabajar en colocar los iconos de redes dentro del header y el botón de python en español debajo del texto, cuando la pantalla es aún mas pequeña lo ajusté verticalmente pero la verdad no me gusta como se vé, además en los artículos algunas imágenes no se ajustan pero aún no lo he revisado

2021-05-03 09:05 UTC, cmaureir commented
No me queda claro si en tu mensaje hay una pregunta sobre lo de los conflictos o todo está OK jaja

También puedes solo mostrar los íconos más pequeños y así no te complicas con moverlos a otro lugar.

2021-05-03 09:17 UTC, cmaureir requested changes
La mayoría son cambios de estilo, me parece bien.
Igual ojalá que no inviertas tanto tiempo en tantos detalles, ya que mientras que la experiencia en desktop y movil muestre las cosas sin que se pongan encima de otras es suficiente.
Mientras más y más detalles sobre margenes o ajustes de detalles, más fácil es que se vayan rompiendo otras cosas.

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +altura{
```suggestion
altura {
```
¿Podemos quizás cambiar este nombre para seguir la tónica de bootstrap y quzás usar `h-100-responsive`?

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +.texto-python_en_espanol{
```suggestion
.texto-python_en_espanol {
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +.texto-plataformas{
```suggestion
.texto-plataformas {
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +  }
```suggestion
}
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +img.ene{
```suggestion
img.ene {
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +.iconos_redes{
```suggestion
.iconos_redes {
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +.iconos_plataformas{
```suggestion
.iconos_plataformas {
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +
```suggestion
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +}
```suggestion
  .texto-plataformas{
    text-align: start;
    padding-left: 0;
  }
  .iconos_plataformas{
    font-size:0.9rem;
    display:inline;
    text-align: start;
    padding-right: 20px; 
  } 

  ul.navbar-nav{ 
    width: auto;
  }
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +    }
```suggestion
  }
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +    align-items: flex-end
```suggestion
      align-items: flex-end
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +    ul.navbar-nav{
```suggestion
    ul.navbar-nav { 
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +
```suggestion
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +      }
```suggestion
    }
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +      }
```suggestion
    } 
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +    }
```suggestion
     width:0;
     height:0;
   }
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> +  display: inline-block;
```suggestion
    display: inline-block;
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/templates/base-index.html
> +                    <div class="iconos_redes"> <!---lg-8 col-md-10 mx-auto">-->
```suggestion
                    <div class="iconos_redes">
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/templates/base-index.html
> +            <!-- <div class="col-auto"> lg-8 col-md-10 mx-auto">-->
```suggestion
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/templates/base-index.html
> +            <!--  </div> -->
```suggestion
```

2021-05-03 09:17 UTC, cmaureir commented on pycltheme/static/css/cl.css
> + .btn-default,
¿por qué es necesario un cambio de btn-primary a un btn-default?

2021-05-05 03:23 UTC, elkabuitrago commented
> No me queda claro si en tu mensaje hay una pregunta sobre lo de los conflictos o todo está OK jaja
> 
> También puedes solo mostrar los íconos más pequeños y así no te complicas con moverlos a otro lugar.

jajaja, pues, no se si te enredo más
resolví el conflicto en el repo de github manualmente como viste y había resuelto en local, pero no hice push de ese merge, ahora no se como va a quedar cuando vuelva a hacer el push 
si hice un pull en local antes de crear el nuevo branch, pero me mostró conflictos porque faltaba algo en main que estaba en local, pero yo misma (fuera de la ley) había previamente hecho el merge en el repo de github, pensé que tal vez lo habías devuelto para revisar o algo, pero quería enfocarme en esos cambios para móvil de todos modos y lo otro eran unas líneas para la paginación que bien podría verlo luego contigo o  volver a incluir e incluso como ves se repiten en todas las plantillas, entonces puede colocarse en el base.html tal vez

Con relación a los íconos más pequeños, si, fue lo que hice al principio, pero me pareció poco práctico (por no decir que de museo) se veían bien pero no podrías usarlos, porque para usarlos  no se podría atinar a hacer click, igual puedo probar y te envío una imagen previo a hacer el push, pero lo que quiero evitar es quitarte mucho tiempo con esto

2021-05-05 03:24 UTC, elkabuitrago commented
> La mayoría son cambios de estilo, me parece bien.
> Igual ojalá que no inviertas tanto tiempo en tantos detalles, ya que mientras que la experiencia en desktop y movil muestre las cosas sin que se pongan encima de otras es suficiente.
> Mientras más y más detalles sobre margenes o ajustes de detalles, más fácil es que se vayan rompiendo otras cosas.

si, pienso igual

2021-05-05 03:30 UTC, elkabuitrago commented on pycltheme/static/css/cl.css
> +altura{
ok, aunque tal vez elimine esa clase, pero entiendo el punto

2021-05-05 03:39 UTC, elkabuitrago commented on pycltheme/static/css/cl.css
> + .btn-default,
porque había una composición de clases (no se si el término existe)  para crear el efecto de borde blanco y botón negro con el btn-primary, pero en móvil se achicaba el borde y se desbordaba el botón, lo mas sencillo era dejar la btn sola y reescribirla para cambiar el color, pero la btn-primary se esta usando en las cards y otros, por eso tomé el btn-default para reescribirla sin afectar lo demás y quité "la composición"

2021-05-05 03:42 UTC, elkabuitrago commented on pycltheme/static/css/cl.css
> +  display: inline-block;
esto es para <401,  creo voy a quitarlo

2021-05-08 13:17 UTC, elkabuitrago commented
> ![Screen Shot 2021-04-24 at 23 07 12](https://user-images.githubusercontent.com/177982/115929984-fce05580-a488-11eb-9ab3-58c46aecc45a.png)
> 
> Sabes si se puede hacer algo para quitar el texto que acompaña al logo o disminuir su trabajo?
> Sigo viendo el index mal en móvil.
> 
> Lo otro, es que veo que este PR tiene conflictos, porque quizás no actualizaste el repo antes de hacer los cambios, tendrías que resolverlos y luego hacer un merge.

disminuí el tamaño del texto "Comunidad Chilena ..." , también disminuí un poco el tamaño del logo 
a ver que te parece, así se ve en "responsive", pero también probé como se ve con otros móviles
hice varios cambios en baseindex.html y en el cl.css
no estoy muy feliz con el comportamiento de la Ñ en la transición de tamaños en la pantalla de computadora, pero si estas de acuerdo, lo dejaría así (ah, no puedes verlo aún)

![image](https://user-images.githubusercontent.com/45636874/117540282-22ff0d00-afd4-11eb-9a64-aaca9c60b257.png)

![image](https://user-images.githubusercontent.com/45636874/117540455-234bd800-afd5-11eb-955e-dd7bb248ccfb.png)

![image](https://user-images.githubusercontent.com/45636874/117540493-7887e980-afd5-11eb-91f2-f826e0cc889c.png)

2021-05-08 16:34 UTC, cmaureir commented
Me parece super @elkabuitrago, cuando termines de limpiar las clases que quizás no vas a usar me avisas y hacemos merge.
Recuerda que para los mini-cambios que hice de espacios y esas cosas, los puedes agregar todos de una, y hacer un commit la respecto, usando la interfaz de github, sin necesidad de hacer los cambios  de nuevo.

2021-05-08 18:10 UTC, elkabuitrago commented
> Me parece super @elkabuitrago, cuando termines de limpiar las clases que quizás no vas a usar me avisas y hacemos merge.
> Recuerda que para los mini-cambios que hice de espacios y esas cosas, los puedes agregar todos de una, y hacer un commit la respecto, usando la interfaz de github, sin necesidad de hacer los cambios de nuevo.

gracias por revisar.
listo, subido
voy a revisar si puedo ajustar las imágenes en los artículos y páginas internas y te aviso

2021-05-17 20:49 UTC, elkabuitrago commented
> > Me parece super @elkabuitrago, cuando termines de limpiar las clases que quizás no vas a usar me avisas y hacemos merge.
> > Recuerda que para los mini-cambios que hice de espacios y esas cosas, los puedes agregar todos de una, y hacer un commit la respecto, usando la interfaz de github, sin necesidad de hacer los cambios de nuevo.
> 
> gracias por revisar.
> listo, subido
> voy a revisar si puedo ajustar las imágenes en los artículos y páginas internas y te aviso

@cmaureir incluí este plugin  https://github.com/pelican-plugins/image-process para ajustar las imágenes en móvil

ahora se ven así:

![image](https://user-images.githubusercontent.com/45636874/118554554-35411f80-b727-11eb-8cea-f3860d283452.png)


![image](https://user-images.githubusercontent.com/45636874/118554444-0f1b7f80-b727-11eb-95c3-8daa5df6f552.png)


![image](https://user-images.githubusercontent.com/45636874/118554222-c6fc5d00-b726-11eb-8260-b7d874b12ec3.png)

2021-05-21 16:42 UTC, cmaureir commented
Me parece super ese plugin @elkabuitrago, te parece que hagamos merge de este PR y luego puedes agregar las otras cosas?

2021-05-21 20:18 UTC, elkabuitrago commented
> Me parece super ese plugin @elkabuitrago, te parece que hagamos merge de este PR y luego puedes agregar las otras cosas?

si @cmaureir , por fa, eso me gustaría, primero hacer merge de lo que estaba pendiente y luego subo lo del plugin
después quiero finalmente incluir una lista de categorías y tags que era lo que originalmente quería hacer hace como un año
te voy avisando 

te cuento, quería incluir este plugin para insertar videos de youtube https://github.com/kura/pelican_youtube/tree/407b97b49112345ea3dfe76f1a5ae41586c4ffb1 pero no me funcionó, no se si hice algo mal (no se que porque es muy simple jajaja) o tenga que ver algo la versión de python etc, la verdad no he revisado el código y no lo veo urgente en lo inmediato, luego lo reviso

2021-05-22 18:34 UTC, merged

2021-05-22 18:34 UTC, cmaureir commented
Muchas gracias por tanto trabajo @elkabuitrago :tada: