Inclusión de opciones de menú Recursos y Eventos
python-chile/pythonchile.cl pull request #62
Opened 2022-03-23 18:59 UTC by elkabuitrago

Recursos:
   - Como organizar una PyDay
   - Enlace a HablemosPython.dev

Eventos:
    - Meetups
    - Pyday Chile
    - PyCon Chile

2022-03-24 20:23 UTC, cmaureir requested changes
dejé un par de comentarios menores.
En general me parece que tiene bastante información y está completo, pero tenemos que ver una estrategia para mejorar la forma de comunicar las idea. Muy personalmente siento que hay muchas secciones, algunas con solo 2 frases, y deberíamos intentar re-organizarlo en algo un poco más 'digerible' y simplificado.

2022-03-24 20:23 UTC, cmaureir commented on content/pages/recursos.md
> +### ¿Como organizar una PyDay?
```suggestion
### ¿Cómo organizar un PyDay?
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/recursos.md
> +* [Organiza una PyDay](/pages/como-organizar-una-pyday.html)
```suggestion
* [Organiza un PyDay](/pages/como-organizar-una-pyday.html) 
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/recursos.md
> +### Hablemos Python
```suggestion
### Python en Español
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/recursos.md
> +En Hablemos Python, el site de Python en Español, encontrarás recursos educativos de conocimiento desde principiante a avanzado:
```suggestion
En el sitio de Python en Español encontrarás recursos educativos de conocimiento desde principiante a avanzado: 
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +En éste enlace encuentras el site con información detallada de las charlas y talleres que se presentaron
```suggestion
En éste enlace encontrarás el sitio con información detallada de las charlas y talleres que se presentaron.
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +El primer evento PyCon Chile se llevó a cabo del 5 al 7 de Noviembre de 2021
```suggestion
La primera PyCon Chile se llevó a cabo del 5 al 7 de Noviembre de 2021
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +* [PyCon2021](https://pycon.cl)
```suggestion
* [PyCon 2021](https://pycon.cl) 
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +* [PyDay2020](https://pyday.cl)
```suggestion
* [PyDay 2020](https://pyday.cl) 
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +En éste enlace encuentras el site con información detallada de las charlas que se presentaron
```suggestion
En éste enlace encontrarás el site con información detallada de las charlas que se presentaron.
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +Hacemos reuniones mensuales en modalidad virtual mientras se mantenga las restricciones por COVID19
```suggestion
Hacemos reuniones mensuales en modalidad virtual mientras se mantenga las restricciones por COVID19.
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +Mira en Youtube los videos de las reuniones anteriores
```suggestion
Mira en Youtube los videos de las reuniones anteriores:
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/eventos.md
> +Estos son los eventos de Python Chile que estan activos o hemos realizado
```suggestion
En esta sección encontrarás los eventos que Python Chile está activamente organizando, o ha realizado anteriormente:
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +#### Encuestas de satisfacción
```suggestion
#### Encuestas luego del evento (_feedback_)
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +Title: Como organizar una PyDay
```suggestion
Title: Cómo organizar un PyDay
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +Title: Como organizar una PyDay
Creo que aunque no sea pregunta lleva tilde ¿no?

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +(Stickers, Poleras/Camiseta, Tazas, Bolsos)
```suggestion
Usualmente las conferencias presenciales suelen incluir: Stickers, Poleras/Camiseta, Tazas, Bolsos, etc. Para ellas es importante:
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +        Programación de publicaciones
```suggestion
        - Programación de publicaciones 
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +        Programación de publicaciones
```suggestion
        - Diseño de anuncios
        - Programación de publicaciones 
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +La difusión incluye tanto la publicación de anuncios programados  en redes sociales oficiales de la organización: Twitter, Facebook, Linkedin como la publicidad pagada y el apoyo de difusión por part
```suggestion
La difusión incluye tanto la publicación de anuncios programados en redes sociales oficiales de la organización: Twitter, Facebook, Linkedin como la publicidad pagada y el apoyo de difusión por parte de organizaciones auspiciantes o colaboradoras.
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +
```suggestion
```

2022-03-24 20:23 UTC, cmaureir commented on content/pages/como_organizar_una_pyday.md
> +En caso de requerir más información o detalles
```suggestion
Queremos compartir nuestra experiencia en la organización de las conferencias de Python: PyDay 2020 y PyCon 2021 con las personas u organizaciones interesadas en organizar conferencias similares localmente en su ciudad o país.
Estas recomendaciones son para organizar una PyDay con un solo track y de participación gratuita, que incluya charlas y talleres.
```
creo que la última frase no iba no? o era continuación?

2022-03-24 21:47 UTC, elkabuitrago commented
Gracias @cmaureir !

2022-03-25 01:30 UTC, elkabuitrago commented
Hice algunos cambios, agrupe algunas secciones, igual podemos ver que tienes en mente para reorganizarlas

2022-07-22 21:38 UTC, merged

2022-07-22 21:38 UTC, cmaureir commented
disculpa la demora Elka :pray: 
muchas gracias!